webtalk_init -webtalk_dir C:/Users/kyrar/OneDrive/Documents/GitHub/DL202030_KyraRose/Lab05/Lab05_project/Lab05_project.sim/sim_1/behav/xsim/xsim.dir/addsub_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 20 16:22:27 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b941025f-f990-4566-8033-db7c937f82b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "16e98e1dd05f4d8680aed826e6954234" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3550U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "120 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 934681856 -regid "" -xml C:/Users/kyrar/OneDrive/Documents/GitHub/DL202030_KyraRose/Lab05/Lab05_project/Lab05_project.sim/sim_1/behav/xsim/xsim.dir/addsub_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/kyrar/OneDrive/Documents/GitHub/DL202030_KyraRose/Lab05/Lab05_project/Lab05_project.sim/sim_1/behav/xsim/xsim.dir/addsub_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/kyrar/OneDrive/Documents/GitHub/DL202030_KyraRose/Lab05/Lab05_project/Lab05_project.sim/sim_1/behav/xsim/xsim.dir/addsub_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
